# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin

      - run:
          name: install dependencies
          command: |
            sudo apt-get -y install pandoc && sudo pip install -e .[dev,test]

      # run tests!
      - run:
          name: run tests
          command: |
            find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | echo
            coverage erase
            coverage run --omit="*tests*,*.virtualenvs/*,*.venv/*,*__init__*" -m unittest discover -v -s . && bash <(curl -s https://codecov.io/bash)

      - run:
          name: run tests reports
          command: |      
            coverage report --show-missing --fail-under=85

      - run:
          name: run static analyzers
          command: | 
            flake8 .
            pylint --enable=E --disable=W,R,C --unsafe-load-any-extension=y example/ naz/ tests/

      # run make upload

      - store_artifacts:
          path: test-reports
          destination: test-reports
